# Generated by Django 3.1.2 on 2021-04-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilep',
            name='Mimg',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobilep',
            name='Mprice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
