# Generated by Django 3.1.2 on 2021-04-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20210418_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilep',
            name='Mname',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
