# Generated by Django 3.1.2 on 2021-04-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_mobilep_mname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eimg', models.ImageField(upload_to='pics')),
                ('Ename', models.TextField()),
                ('Eprice', models.IntegerField()),
            ],
        ),
    ]
