# Generated by Django 3.1.2 on 2021-04-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homedeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hdimg', models.ImageField(upload_to='pics')),
                ('Hdname', models.TextField()),
                ('Hdprice', models.IntegerField()),
            ],
        ),
    ]
