# Generated by Django 3.1.2 on 2021-04-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_homedeal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobilesp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mimg', models.ImageField(upload_to='pics')),
                ('Mname', models.TextField()),
                ('Mprice', models.IntegerField()),
                ('Mstyle', models.TextField()),
                ('Mcolor', models.TextField()),
                ('Mcamera', models.TextField()),
                ('Msize', models.TextField()),
                ('Mmemory', models.TextField()),
                ('Mbattry', models.TextField()),
                ('Mwarranty', models.TextField()),
                ('Mother', models.TextField()),
            ],
        ),
    ]
