# Generated by Django 3.1.2 on 2021-05-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_mobilesp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indexs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Isimg', models.ImageField(upload_to='pics')),
                ('Isprice', models.IntegerField()),
                ('Issize', models.IntegerField()),
                ('Iscolor', models.TextField()),
            ],
        ),
    ]
