# Generated by Django 3.1.2 on 2021-05-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_indexs'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexs',
            name='Isname',
            field=models.TextField(default='', editable=False, max_length=50),
        ),
    ]
