# Generated by Django 3.1.2 on 2021-05-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_indexs_isname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Esimg', models.ImageField(upload_to='pics')),
                ('Esname', models.TextField()),
                ('Esprice', models.IntegerField()),
                ('Essize', models.IntegerField()),
                ('Esother', models.TextField()),
            ],
        ),
    ]
