# Generated by Django 3.1.2 on 2021-05-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_elecs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elecs',
            name='Essize',
            field=models.TextField(),
        ),
    ]
