# Generated by Django 3.1.2 on 2021-05-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_featspc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pimg', models.ImageField(upload_to='pics')),
                ('Pname', models.TextField()),
                ('Pprice', models.IntegerField()),
            ],
        ),
    ]
